### ISSUE TITLE
coconatfly installation 

### ISSUE THREAD

**Issue by denertekin** [natverse/coconatfly#6]
Hi, 
I am trying to install coconatfly, following the tutorial here: https://natverse.org/coconatfly/articles/getting-started.html
i get an error saying "Error: Failed to install 'coconatfly' from GitHub:
  cannot open URL 'https://api.github.com/repos/flyconnectome/malecns/contents/DESCRIPTION?ref=HEAD'", as I don't have access to malecns.. 
Is there a way I can still install hemibrain and flywire data (and skip malecns installation) ?

thank you!

**Comment by jefferis** [comment]
hi @denertekin, thanks for your interest and sorry for the install issue. It should be fixed now.

**Comment by jefferis** [comment]
Hello @denertekin if the latest coconatfly update installed ok for you it would be great if you could close this issue. With many thanks, Greg.

**Comment by denertekin** [comment]
Hi Greg, Yes all installed ok now! 
Thank you
Deniz
