### ISSUE TITLE
Connectivity data for flywire

### ISSUE THREAD

**Issue by denertekin** [natverse/coconatfly#8]
Hi Greg, 
I'm getting an error when i try to map flywire neuron partners. 
"Error in flywire_connectome_file(type, version = version, cached = cached)
path" .../syn_proof_analysis_filtered_630.feather does not exist!"

i installed the fw data from:
fafbseg::[download_flywire_release_data](https://rdrr.io/pkg/fafbseg/man/download_flywire_release_data.html)()

Deniz

**Comment by jefferis** [comment]
Dear Deniz, thanks for this report. Is that the full error message? If so there’s something funny about the path. Can you put the results of 

fafbseg:::flywire_connectome_basedir()

And for good measure 

dr_fafbseg()

Thanks, Greg

**Comment by denertekin** [comment]
Hi Greg, no it is not the full path, here is the full path. 

> fafbseg:::flywire_connectome_basedir()
[1] "C:\\Users\\uqdertek\\AppData\\Local/R/fafbseg/flywire_connectome_analysis_data/R/fafbseg/flywire_connectome_analysis_data"

and 
dr_fafbseg()

R packages
----
fafbseg package:
Version: 0.13
GithubSHA1: 5617c7516a3cda69eb9ab622399cc19097d3b168
Packaged: 2023-08-28 07:39:11 UTC; uqdertek

-- File: 
R arrow package:  7.0.0 
FlyWire
----
Checking secrets folder for tokens from R: C:/Users/uqdertek/.cloudvolume/secrets 
Valid FlyWire ChunkedGraph token is set and found by R!
Please use simple_python to install python+cloudvolume for full access to flywire API!

1 FlyWire/CloudVolume credential files available at
C:/Users/uqdertek/.cloudvolume/secrets
[1] "cave-secret.json"
Error : invalid version specification ‘NA’

Flywire cloudvolume URL: graphene://https://prod.flywire-daf.com/segmentation/table/fly_v31
Google FFN1 segmentation
----
* Set the `fafbseg.skelziproot` option:
   `options(fafbseg.skelziproot="/path/to/zips")` 
  if you want to use FFN1 skeleton files!

Python
----
python:         C:/Users/uqdertek/AppData/Local/Programs/Python/Python311/python.exe
libpython:      C:/Users/uqdertek/AppData/Local/Programs/Python/Python311/python311.dll
pythonhome:     C:/Users/uqdertek/AppData/Local/Programs/Python/Python311
version:        3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]

NOTE: Python version was forced by use_python function

Error in `$<-.data.frame`(`*tmp*`, "installed", value = TRUE) : 
  replacement has 1 row, data has 0

**Comment by jefferis** [comment]
Thanks. I see the problem and I’ll be able to fix. Sorry this package has already been used & tested quite a lot on mac/Linux but you are doing the testing on Windows which is unfortunately not a development platform for us. Should be fixed tomorrow.

**Comment by jefferis** [comment]
@denertekin please restart R, update the fafbseg package 

```
natmanager::install(pkgs="fafbseg")
```

And then try again and the data downloads should behave. Thanks for helping to debug on windows.

**Comment by denertekin** [comment]
Hi Greg, 

thank you very much, they are behaving!
